IMAGE_DIR: '/home/jliao/rosbags/2021-10-26-17-08-32/avt_cameras_camera6_image_color_compressed/'
SAVE_DIR: '/home/jliao/yolov5-face/output_dir/avt_cameras_camera6/'
# SAVE_TRACKING: False
# TRACK_ONLY: True
# WRITE_VIDEO: False
# DISPLAY_RESULTS: True
# DISPLAY_CROP: True

LPD:
  WEIGHTS: '/home/jliao/anonymization/weights/lpd.pt'
  CONF_THRES: 0.5
  IOU_THRES: 0.45
  IMAGE_SIZE: 1024