IMAGE_DIR: '/local/home/jliao/rosbags/2021-10-26-17-08-32/avt_cameras_camera6_image_color_compressed/'
SAVE_DIR: '/local/home/jliao/yolov5-face/output_dir/avt_cameras_camera6/'
SAVE_TRACKING: False
TRACK_ONLY: True
WRITE_VIDEO: False
DISPLAY_RESULTS: True
DISPLAY_YOLO5FACE: True
DISPLAY_PIFPAF: True
PREDICT_PIFPAF_HEAD: True
DISPLAY_CROP: True

# Face Detector parameters
FACE_DETECTOR:
  WEIGHTS: '/local/home/jliao/anonymization/weights/face.pt'
  IMAGE_SIZE: 800
  CONF_THRES: 0.3
  IOU_THRES: 0.5

# Pose Detector parameters
POSE_DETECTOR:
  WEIGHTS: 'shufflenetv2k30'

# License Plate Detector parameters
LPD:
  CLASSES: './data/classes/custom.names'
  WEIGHTS: '/local/home/jliao/anonymization/weights/yolov4-416'
  ANCHORS: [12,16, 19,36, 40,28, 36,75, 76,55, 72,146, 142,110, 192,243, 459,401]
  STRIDES: [8, 16, 32]
  XYSCALE: [1.2, 1.1, 1.05]
  ANCHOR_PER_SCALE: 3
  IOU_LOSS_THRES: 0.5
  CONF_THRES: 0.3
  IOU_THRES: 0.5
  RESIZE: 416

# Tracker paraemters
TRACKER:
  MAX_AGE: 5
  MIN_HITS: 1
  IOU_THRES: 0.3
  DISTANCE_THRESHOLD: 100
  SIZE_DIST_RATIO: 0.3